using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nestacular.NESCore.CPU.Opcodes
{
    static internal class OP
    {
        static internal Action JAM()
        {
            while (true) {  }
        }
        static internal Action ADC()
        { return null; }
        static internal Action AND()
        { return null; }
        static internal Action ASL() 
        { return null; }
        static internal Action BCC() 
        { return null; }
        static internal Action BCS()
        { return null; }
        static internal Action BEQ()
        { return null; }
        static internal Action BIT()
        { return null; }
        static internal Action BMI()
        { return null; }
        static internal Action BNE()
        { return null; }
        static internal Action BPL() 
        { return null; }
        static internal Action BRK()
        { return null; }
        static internal Action BVC() 
        { return null; }
        static internal Action BVS()
        { return null; }
        static internal Action CLC()
        { return null; }
        static internal Action CLI() 
        { return null; }
        static internal Action CLV() 
        { return null; }
        static internal Action CMP()
        { return null; }
        static internal Action CPX()
        { return null; }
        static internal Action CPY()
        { return null; }
        static internal Action DEC()
        { return null; }
        static internal Action DEX()
        { return null; }
        static internal Action DEY()
        { return null; }
        static internal Action EOR()
        { return null; }
        static internal Action INC()
        { return null; }
        static internal Action INX()
        { return null; }
        static internal Action INY()
        { return null; }
        static internal Action JMP() 
        { return null; }
        static internal Action JSR()
        { return null; }
        static internal Action LDA()
        { return null; }
        static internal Action LDX() 
        { return null; }
        static internal Action LDY()
        { return null; }
        static internal Action LSR()
        { return null; }
        static internal Action NOP() 
        { return null; }
        static internal Action ORA()
        { return null; }
        static internal Action PHA() 
        { return null; }
        static internal Action PHP()
        { return null; }
        static internal Action PLA() 
        { return null; }
        static internal Action PLP() 
        { return null; }
        static internal Action ROL() 
        { return null; }
        static internal Action ROR() 
        { return null; }
        static internal Action RTI()
        { return null; }
        static internal Action RTS() 
        { return null; }
        static internal Action SBC()
        { return null; }
        static internal Action SEC() 
        { return null; }
        static internal Action SED()
        { return null; }
        static internal Action SEI() 
        { return null; }
        static internal Action STA() 
        { return null; }
        static internal Action STX() 
        { return null; }
        static internal Action STY() 
        { return null; }
        static internal Action TAX()
        { return null; }
        static internal Action TAY()
        { return null; }
        static internal Action TSX()
        { return null; }
        static internal Action TXS()
        { return null; }
        static internal Action TYA()
        { return null; }
        static internal Action SLO()
        { return null; }
        static internal Action ANC()
        { return null; }
        static internal Action RLA()
        { return null; }
        static internal Action SRE() 
        { return null; }
        static internal Action ALR()
        { return null; }
        static internal Action RRA()
        { return null; }
        static internal Action ARR() 
        { return null; }
        static internal Action SAX() 
        { return null; }
        static internal Action TXA()
        { return null; }
        static internal Action ANE()
        { return null; }
        static internal Action SHA()
        { return null; }
        static internal Action TAS() 
        { return null; }
        static internal Action ISC()
        { return null; }
        static internal Action USBC() 
        { return null; }
        static internal Action DCP()
        { return null; }
        static internal Action LAX()
        { return null; }
        static internal Action SHY()
        { return null; }
        static internal Action SHX()
        { return null; }
        static internal Action LXA() 
        { return null; }
        static internal Action LAS() 
        { return null; }
        static internal Action SBX()
        { return null; }
        static internal Action CLD()
        { return null; }
    }
    static internal class Mode
    {
        static internal Action Immediate() 
        { return null; }
        static internal Action XIndirect() 
        { return null; }
        static internal Action YIndirect() 
        { return null; }
        static internal Action Absolute() 
        { return null; }
        static internal Action XAbsolute() 
        { return null; }
        static internal Action YAbsolute()
        { return null; }
        static internal Action Implied() 
        { return null; }
        static internal Action Indirect()
        { return null; }
        static internal Action Relative() 
        { return null; }
        static internal Action ZeroPage() 
        { return null; }
        static internal Action XZeroPage() 
        { return null; }
        static internal Action YZeroPage()
        { return null; }

    }

}
